---
abstract: 'Object system for filesystem paths.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.16
  ExtUtils::MakeMaker: 6.36
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Object
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.14
  Error::Pure: 0.3
  File::Spec::Functions: 0
  FindBin: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/File-Object/issues
  homepage: https://github.com/michal-josef-spacek/File-Object
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/File-Object
version: '0.16'
