---
abstract: 'Object system for filesystem paths.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Object
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.01
  Error::Pure: 0.01
  File::Spec::Functions: 0
  FindBin: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository:
    type: git
    url: git://github.com/tupinek/File-Object
    web: https://github.com/tupinek/File-Object
version: 0.03
